import { Project, PlatformStats, Comment, ProjectUpdate } from '@/types';

export const mockProjects: Project[] = [
    {
        id: '1',
        title: 'EcoBishkek — Умные урны для сортировки',
        shortDescription: 'Установка умных урн с датчиками заполненности в парках Бишкека для раздельного сбора мусора.',
        description: `EcoBishkek — инновационный проект по установке умных урн с датчиками заполненности в парках Бишкека. Каждая урна оснащена IoT-датчиком, который уведомляет коммунальные службы о заполненности, оптимизируя маршруты сбора.\n\nНаша цель — установить 200 умных урн в 10 крупнейших парках города к концу года. Каждая урна позволяет сортировать отходы на 3 категории: пластик, бумага и общие отходы.\n\nПроект поддержан мэрией Бишкека и экологическими организациями.`,
        category: 'technology',
        authorId: 'u1',
        authorName: 'Айбек Касымов',
        authorAvatar: '',
        coverImage: '/images/projects/eco.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 500000,
        currentAmount: 342500,
        backersCount: 156,
        fundingType: 'all-or-nothing',
        projectType: 'reward',
        status: 'active',
        deadline: '2026-04-15',
        createdAt: '2026-02-01',
        updatedAt: '2026-03-01',
        likes: 89,
        featured: true,
        rewards: [
            { id: 'r1', projectId: '1', title: 'Благодарность', description: 'Ваше имя на стикере урны + благодарственное письмо', minAmount: 500, quantityAvailable: 500, quantityClaimed: 120 },
            { id: 'r2', projectId: '1', title: 'Эко-набор', description: 'Многоразовая сумка + бутылка + стикер', minAmount: 2000, quantityAvailable: 100, quantityClaimed: 45 },
            { id: 'r3', projectId: '1', title: 'Спонсор урны', description: 'Ваш логотип на одной из умных урн', minAmount: 25000, quantityAvailable: 20, quantityClaimed: 8 },
        ],
    },
    {
        id: '2',
        title: 'Кыргыз Тили — Мобильное приложение',
        shortDescription: 'Интерактивное приложение для изучения кыргызского языка с играми и аудио от носителей.',
        description: `Создаём мобильное приложение для изучения кыргызского языка, доступное на iOS и Android. Приложение использует геймификацию и интерактивные упражнения.\n\nОсобенности:\n- 50 уроков с аудио от носителей\n- Игровые механики\n- Система достижений\n- Разговорник для путешественников\n- Офлайн-режим`,
        category: 'education',
        authorId: 'u2',
        authorName: 'Нурзат Абдыкерим кызы',
        authorAvatar: '',
        coverImage: '/images/projects/language.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 300000,
        currentAmount: 285000,
        backersCount: 234,
        fundingType: 'flexible',
        projectType: 'reward',
        status: 'active',
        deadline: '2026-03-30',
        createdAt: '2026-01-15',
        updatedAt: '2026-03-01',
        likes: 167,
        featured: true,
        rewards: [
            { id: 'r4', projectId: '2', title: 'Ранний доступ', description: 'Бета-доступ к приложению + бессрочная премиум-подписка', minAmount: 1000, quantityAvailable: 300, quantityClaimed: 180 },
            { id: 'r5', projectId: '2', title: 'Учитель', description: 'Персональный урок с создателем приложения', minAmount: 5000, quantityAvailable: 30, quantityClaimed: 22 },
        ],
    },
    {
        id: '3',
        title: 'Nomad Coffee — Кофейня-коворкинг',
        shortDescription: 'Открытие кофейни-коворкинга в центре Бишкека для фрилансеров и стартапов.',
        description: `Nomad Coffee — это не просто кофейня. Это пространство для создателей, фрилансеров и стартаперов Кыргызстана.\n\nМы создаём место, где инновации рождаются за чашкой кофе из местных обжаренных зёрен.\n\nПланы:\n- 50 рабочих мест\n- Переговорные комнаты\n- Сцена для митапов\n- Высокоскоростной интернет\n- Зона отдыха`,
        category: 'business',
        authorId: 'u3',
        authorName: 'Тимур Жумагулов',
        authorAvatar: '',
        coverImage: '/images/projects/coffee.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 1200000,
        currentAmount: 480000,
        backersCount: 89,
        fundingType: 'all-or-nothing',
        projectType: 'reward',
        status: 'active',
        deadline: '2026-05-20',
        createdAt: '2026-02-10',
        updatedAt: '2026-03-01',
        likes: 124,
        rewards: [
            { id: 'r6', projectId: '3', title: 'Кофе навсегда', description: '1 бесплатный кофе в день в течение месяца', minAmount: 3000, quantityAvailable: 200, quantityClaimed: 67 },
            { id: 'r7', projectId: '3', title: 'VIP Резидент', description: 'Персональное рабочее место на 3 месяца', minAmount: 15000, quantityAvailable: 30, quantityClaimed: 12 },
        ],
    },
    {
        id: '4',
        title: 'Помощь школам Нарына',
        shortDescription: 'Сбор средств на оборудование компьютерных классов в 5 школах Нарынской области.',
        description: `В Нарынской области многие школы не имеют современного компьютерного оборудования. Мы собираем средства на оснащение 5 школ компьютерными классами.\n\nКаждый класс будет оснащён:\n- 15 ноутбуков\n- Проектор\n- Интерактивная доска\n- Высокоскоростной интернет через Starlink`,
        category: 'social',
        authorId: 'u4',
        authorName: 'Фонд "Билим"',
        authorAvatar: '',
        coverImage: '/images/projects/school.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 800000,
        currentAmount: 620000,
        backersCount: 312,
        fundingType: 'flexible',
        projectType: 'donation',
        status: 'active',
        deadline: '2026-04-01',
        createdAt: '2026-01-20',
        updatedAt: '2026-03-01',
        likes: 298,
        featured: true,
        rewards: [
            { id: 'r8', projectId: '4', title: 'Благодарность', description: 'Письмо от учеников школы', minAmount: 500, quantityAvailable: 1000, quantityClaimed: 290 },
        ],
    },
    {
        id: '5',
        title: 'ArtAlay — Фестиваль уличного искусства',
        shortDescription: 'Организация первого фестиваля уличного искусства с международными художниками в Бишкеке.',
        description: `ArtAlay — первый международный фестиваль уличного искусства в Бишкеке.\n\nМы приглашаем 20 художников из 10 стран для создания муралов на зданиях города. Фестиваль также включает мастер-классы, выставки и концерт.`,
        category: 'creative',
        authorId: 'u5',
        authorName: 'Асель Бакирова',
        authorAvatar: '',
        coverImage: '/images/projects/art.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 450000,
        currentAmount: 198000,
        backersCount: 78,
        fundingType: 'all-or-nothing',
        projectType: 'reward',
        status: 'active',
        deadline: '2026-06-01',
        createdAt: '2026-02-20',
        updatedAt: '2026-03-01',
        likes: 156,
        rewards: [
            { id: 'r9', projectId: '5', title: 'Билет на фестиваль', description: 'VIP-билет на все мероприятия фестиваля', minAmount: 2000, quantityAvailable: 200, quantityClaimed: 45 },
            { id: 'r10', projectId: '5', title: 'Авторский принт', description: 'Подписанный принт от одного из художников', minAmount: 5000, quantityAvailable: 50, quantityClaimed: 18 },
        ],
    },
    {
        id: '6',
        title: 'Тaza Суу — Чистая вода для сёл',
        shortDescription: 'Установка систем фильтрации воды в 10 сёлах Иссык-Кульской области.',
        description: `Проект направлен на обеспечение чистой питьевой водой жителей отдалённых сёл Иссык-Кульской области.\n\nМы устанавливаем современные системы фильтрации воды, которые обслуживают до 500 человек каждая.`,
        category: 'social',
        authorId: 'u6',
        authorName: 'NGO WaterKG',
        authorAvatar: '',
        coverImage: '/images/projects/water.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 950000,
        currentAmount: 712500,
        backersCount: 445,
        fundingType: 'flexible',
        projectType: 'donation',
        status: 'active',
        deadline: '2026-04-10',
        createdAt: '2026-01-10',
        updatedAt: '2026-03-01',
        likes: 512,
        featured: true,
        rewards: [
            { id: 'r11', projectId: '6', title: 'Именная табличка', description: 'Ваше имя на табличке у источника воды', minAmount: 1000, quantityAvailable: 500, quantityClaimed: 380 },
        ],
    },
    {
        id: '7',
        title: 'KyrgyzTech Hub — Акселератор',
        shortDescription: 'Создание первого технологического акселератора для стартапов Центральной Азии.',
        description: `KyrgyzTech Hub — акселератор нового поколения для технологических стартапов Кыргызстана и Центральной Азии.\n\nПрограмма на 3 месяца включает менторство, инвестиции и доступ к глобальной сети партнёров.`,
        category: 'technology',
        authorId: 'u7',
        authorName: 'Эрлан Сатыбалдиев',
        authorAvatar: '',
        coverImage: '/images/projects/tech.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 2000000,
        currentAmount: 850000,
        backersCount: 67,
        fundingType: 'all-or-nothing',
        projectType: 'reward',
        status: 'active',
        deadline: '2026-07-01',
        createdAt: '2026-02-15',
        updatedAt: '2026-03-01',
        likes: 203,
        rewards: [
            { id: 'r12', projectId: '7', title: 'Стартап-билет', description: 'Билет на Demo Day + нетворкинг', minAmount: 5000, quantityAvailable: 100, quantityClaimed: 34 },
            { id: 'r13', projectId: '7', title: 'Партнёр', description: 'Логотип на материалах + VIP-статус', minAmount: 50000, quantityAvailable: 10, quantityClaimed: 3 },
        ],
    },
    {
        id: '8',
        title: 'Шелковый Путь — Документальный фильм',
        shortDescription: 'Съёмки документального фильма о современном Шёлковом пути через Кыргызстан.',
        description: `Документальный фильм о людях, живущих вдоль древнего Шёлкового пути в Кыргызстане. Мы проедем от Оша до Бишкека, собирая истории торговцев, ремесленников и кочевников.`,
        category: 'creative',
        authorId: 'u8',
        authorName: 'Студия "Кыргыз Фильм"',
        authorAvatar: '',
        coverImage: '/images/projects/film.jpg',
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        gallery: [],
        goalAmount: 650000,
        currentAmount: 195000,
        backersCount: 102,
        fundingType: 'flexible',
        projectType: 'reward',
        status: 'active',
        deadline: '2026-05-15',
        createdAt: '2026-02-25',
        updatedAt: '2026-03-01',
        likes: 178,
        rewards: [
            { id: 'r14', projectId: '8', title: 'В титрах', description: 'Ваше имя в титрах фильма', minAmount: 1000, quantityAvailable: 500, quantityClaimed: 78 },
            { id: 'r15', projectId: '8', title: 'Премьера', description: 'VIP-приглашение на премьеру', minAmount: 5000, quantityAvailable: 50, quantityClaimed: 12 },
        ],
    },
];

export const mockComments: Comment[] = [
    { id: 'c1', userId: 'u10', userName: 'Алина Н.', userAvatar: '', projectId: '1', content: 'Отличный проект! Давно пора заняться экологией в наших парках. Поддерживаю!', createdAt: '2026-03-01' },
    { id: 'c2', userId: 'u11', userName: 'Бакыт К.', userAvatar: '', projectId: '1', content: 'А можно установить такие урны и в жилых районах? Готов поддержать ещё больше!', createdAt: '2026-03-02' },
    { id: 'c3', userId: 'u12', userName: 'Сергей М.', userAvatar: '', projectId: '1', content: 'Как IoT-разработчик, я впечатлён техническим решением. Желаю успехов!', createdAt: '2026-03-03' },
    { id: 'c4', userId: 'u13', userName: 'Динара А.', userAvatar: '', projectId: '2', content: 'Наконец-то кто-то делает приложение для кыргызского языка! 🎉', createdAt: '2026-02-28' },
    { id: 'c5', userId: 'u14', userName: 'Максат Т.', userAvatar: '', projectId: '2', content: 'Мои дети будут рады такому приложению. Поддержал!', createdAt: '2026-03-01' },
];

export const mockUpdates: ProjectUpdate[] = [
    { id: 'up1', projectId: '1', title: 'Первая партия урн заказана!', content: 'Мы заказали первую партию из 50 умных урн у производителя. Доставка ожидается через 3 недели.', createdAt: '2026-03-01' },
    { id: 'up2', projectId: '1', title: 'Партнёрство с мэрией', content: 'Подписан меморандум о сотрудничестве с мэрией Бишкека для размещения урн.', createdAt: '2026-02-20' },
    { id: 'up3', projectId: '2', title: 'Бета-версия готова!', content: 'Мы завершили разработку бета-версии приложения. Первые 100 бэкеров получат доступ на следующей неделе.', createdAt: '2026-03-02' },
];

export const platformStats: PlatformStats = {
    totalProjects: 156,
    totalFunded: 89,
    totalBackers: 4523,
    totalRaised: 12450000,
};

export function formatCurrency(amount: number): string {
    return new Intl.NumberFormat('ru-RU').format(amount);
}

export function getProgress(current: number, goal: number): number {
    return Math.min(Math.round((current / goal) * 100), 100);
}

export function getDaysLeft(deadline: string): number {
    const now = new Date();
    const end = new Date(deadline);
    const diff = end.getTime() - now.getTime();
    return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}

export function getCategoryIcon(category: string): string {
    const icons: Record<string, string> = {
        business: '💼',
        technology: '🚀',
        education: '📚',
        social: '🤝',
        creative: '🎨',
    };
    return icons[category] || '📦';
}
